version: '3.7'

services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: symfony
      MYSQL_USER: symfony
      MYSQL_PASSWORD: example
    volumes:
      - ./docker/mysql:/var/lib/mysql
  web:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    volumes:
      - ./:/var/www
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: mysql://symfony:example@db/symfony
    depends_on:
      - db