create_message:
  path: /
  controller: App\ApiBundle\Controller\MessageController::createMessageAction
  methods: [POST]

get_message:
  path: /
  controller: App\ApiBundle\Controller\MessageController::getMessageAction
  methods: [ GET ]